apiVersion: v1
kind: Service
metadata:
  name: aibot-nats
spec:
  selector:
    app.kubernetes.io/name: aibot-nats
  ports:
    - name: client
      port: 4222
      targetPort: client
    - name: monitor
      port: 8222
      targetPort: monitor
