package context

import (
	"encoding/json"
	"errors"
	"strings"
	"time"

	"github.com/askie/grix/backend/internal/llm/provider"
	"github.com/askie/grix/backend/internal/model"
	"github.com/askie/grix/backend/internal/pkg/textutil"
	"github.com/askie/grix/backend/internal/store"
	"github.com/askie/grix/backend/internal/ws/protocol"
	"gorm.io/gorm"
)

const (
	maxSystemTokens     = 500
	maxRAGTokens        = 2000
	maxRecentMessages   = 20
	maxHistoryTokens    = 1800
	maxHistoryMsgTokens = 240
	maxUserInputTokens  = 600
)

// PromptStats captures prompt sizing diagnostics using rough token estimates.
type PromptStats struct {
	TotalMessages   int
	EstimatedTokens int
	SystemTokens    int
	RAGTokens       int
	HistoryMessages int
	HistoryTokens   int
	UserInputTokens int
	UserInputDedup  bool
}

// BuildPrompt assembles the LLM prompt from system prompt, RAG context,
// recent messages, and user input.
func BuildPrompt(sessionID string, agent *model.Agent, userInput string, ragContext []string) []provider.Message {
	messages, _ := BuildPromptWithStats(sessionID, agent, userInput, ragContext)
	return messages
}

// BuildPromptWithStats assembles prompt messages and returns sizing stats.
func BuildPromptWithStats(
	sessionID string,
	agent *model.Agent,
	userInput string,
	ragContext []string,
) ([]provider.Message, PromptStats) {
	return BuildPromptForUserWithStats(sessionID, 0, agent, userInput, ragContext)
}

func BuildPromptForContextMessagesWithStats(
	agent *model.Agent,
	userInput string,
	ragContext []string,
	contextMessages []protocol.ContextMessagePayload,
) ([]provider.Message, PromptStats) {
	history := buildHistoryFromContextMessages(contextMessages)
	return buildPromptWithHistory(agent, userInput, ragContext, history)
}

// isDelegateOrigin checks whether a message was generated by AI delegation
// by inspecting the extra JSON field for {"delegate_origin":true}.
func isDelegateOrigin(extra json.RawMessage) bool {
	if len(extra) == 0 {
		return false
	}
	var m map[string]interface{}
	if err := json.Unmarshal(extra, &m); err != nil {
		return false
	}
	v, ok := m["delegate_origin"]
	if !ok {
		return false
	}
	b, _ := v.(bool)
	return b
}

// mergeConsecutiveRoles merges adjacent messages with the same role by
// concatenating their content with a newline separator.
// LLM APIs expect strict user/assistant alternation; consecutive same-role
// messages (e.g. human supplements after a delegate reply) would break this.
func mergeConsecutiveRoles(msgs []provider.Message) []provider.Message {
	if len(msgs) <= 1 {
		return msgs
	}
	merged := make([]provider.Message, 0, len(msgs))
	merged = append(merged, msgs[0])
	for i := 1; i < len(msgs); i++ {
		last := &merged[len(merged)-1]
		if msgs[i].Role == last.Role && msgs[i].Role != "system" {
			last.Content = last.Content + "\n" + msgs[i].Content
		} else {
			merged = append(merged, msgs[i])
		}
	}
	return merged
}

// BuildPromptForUserWithStats assembles prompt messages with per-user history reset filtering.
func BuildPromptForUserWithStats(
	sessionID string,
	userID int64,
	agent *model.Agent,
	userInput string,
	ragContext []string,
) ([]provider.Message, PromptStats) {
	// Recent messages from the session
	var recentMsgs []model.Message
	if store.DB != nil {
		query := store.DB.Where(
			"session_id = ? AND is_deleted = false AND is_revoked = false AND msg_type IN ?",
			sessionID,
			[]int16{1, 5},
		)
		if cutoff, ok := loadHistoryCutoff(sessionID, userID); ok {
			query = query.Where("created_at > ?", cutoff)
		}
		// 群聊成员的上下文同样不能越过 joined_at：否则新成员一句提问，
		// AI 可能把入群前的群聊内容读进 prompt 并在回复中泄露给本人。
		// 与 /messages/history(buildVisibleSessionMessageQuery) 口径一致。
		if userID > 0 {
			if joinedAt, isGroup, ok := loadGroupMemberJoinedAt(sessionID, userID); ok && isGroup && !joinedAt.IsZero() {
				query = query.Where("created_at >= ?", joinedAt)
			}
		}
		// Filter out messages restricted by visible_to that this user cannot see.
		if store.IsPostgres() && userID > 0 {
			query = query.Where(
				"visible_to IS NULL OR sender_id = ? OR visible_to @> to_jsonb(?::bigint)",
				userID, userID,
			)
		}
		query.
			Order("msg_id DESC").
			Limit(maxRecentMessages).
			Find(&recentMsgs)
	}

	// Keep recent history under a fixed token budget.
	selected := make([]provider.Message, 0, maxRecentMessages)
	historyTokenBudget := maxHistoryTokens
	for i := 0; i < len(recentMsgs); i++ {
		msg := recentMsgs[i] // DESC: newest -> oldest
		role := "user"
		if msg.SenderType == 2 || isDelegateOrigin([]byte(msg.Extra)) {
			role = "assistant"
		}
		content := strings.TrimSpace(msg.Content)
		if content == "" {
			continue
		}
		content = textutil.TruncateRunes(content, maxHistoryMsgTokens*2)
		tokens := estimateTokensApprox(content)
		if tokens <= 0 {
			continue
		}
		if tokens > historyTokenBudget {
			content = textutil.TruncateRunes(content, historyTokenBudget*2)
			tokens = estimateTokensApprox(content)
			if tokens <= 0 {
				break
			}
		}
		selected = append(selected, provider.Message{
			Role:    role,
			Content: content,
		})
		historyTokenBudget -= tokens
		if historyTokenBudget <= 0 {
			break
		}
	}

	// Reverse selected history to chronological order.
	chronological := make([]provider.Message, 0, len(selected))
	for i := len(selected) - 1; i >= 0; i-- {
		chronological = append(chronological, selected[i])
	}

	return buildPromptWithHistory(agent, userInput, ragContext, chronological)
}

func loadHistoryCutoff(sessionID string, userID int64) (time.Time, bool) {
	if store.DB == nil || sessionID == "" || userID <= 0 {
		return time.Time{}, false
	}
	var reset model.SessionHistoryReset
	err := store.DB.Select("deleted_before").
		Where("session_id = ? AND user_id = ?", sessionID, userID).
		First(&reset).Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return time.Time{}, false
		}
		return time.Time{}, false
	}
	return reset.DeletedBefore, !reset.DeletedBefore.IsZero()
}

// loadGroupMemberJoinedAt 返回该用户在会话中的 joined_at 以及会话是否为群聊。
// 非成员或非人类成员返回 ok=false，调用方按不过滤处理。
func loadGroupMemberJoinedAt(sessionID string, userID int64) (joinedAt time.Time, isGroup bool, ok bool) {
	if store.DB == nil || sessionID == "" || userID <= 0 {
		return time.Time{}, false, false
	}
	var row struct {
		JoinedAt    time.Time `gorm:"column:joined_at"`
		SessionType int16     `gorm:"column:session_type"`
	}
	err := store.DB.Table("session_members AS me").
		Select("me.joined_at, s.session_type").
		Joins("JOIN sessions AS s ON s.session_id = me.session_id").
		Where("me.session_id = ? AND me.member_id = ? AND me.member_type = 1", sessionID, userID).
		Take(&row).Error
	if err != nil {
		return time.Time{}, false, false
	}
	// messages.created_at 入库时统一转 UTC（model.Message.BeforeCreate），
	// joined_at 与 created_at 比较前必须对齐到同一时间轴，否则 SQLite 下
	// 本地时区的 joined_at 会把入群后的消息也误过滤掉。
	return row.JoinedAt.UTC(), row.SessionType == model.SessionTypeGroup, true
}

func estimateTokensApprox(content string) int {
	if content == "" {
		return 0
	}
	runes := len([]rune(content))
	if runes <= 0 {
		return 0
	}
	return (runes + 1) / 2
}

func buildPromptWithHistory(
	agent *model.Agent,
	userInput string,
	ragContext []string,
	history []provider.Message,
) ([]provider.Message, PromptStats) {
	messages := make([]provider.Message, 0)
	stats := PromptStats{}

	if agent != nil {
		systemContent := agent.SystemPrompt
		if agent.ProviderType == model.AgentProviderLocal && agent.ContextFile != "" {
			systemContent = agent.ContextFile
		}
		systemContent = strings.TrimSpace(systemContent)
		if systemContent != "" {
			systemContent = textutil.TruncateRunes(systemContent, maxSystemTokens*2)
			messages = append(messages, provider.Message{
				Role:    "system",
				Content: systemContent,
			})
			stats.SystemTokens = estimateTokensApprox(systemContent)
			stats.EstimatedTokens += stats.SystemTokens
		}
	}

	if len(ragContext) > 0 {
		ragText := "以下是相关的历史上下文信息：\n" + strings.Join(ragContext, "\n---\n")
		ragText = textutil.TruncateRunes(ragText, maxRAGTokens*2)
		messages = append(messages, provider.Message{
			Role:    "system",
			Content: ragText,
		})
		stats.RAGTokens = estimateTokensApprox(ragText)
		stats.EstimatedTokens += stats.RAGTokens
	}

	history = mergeConsecutiveRoles(history)
	messages = append(messages, history...)
	stats.HistoryMessages = len(history)
	for _, item := range history {
		stats.HistoryTokens += estimateTokensApprox(item.Content)
	}
	stats.EstimatedTokens += stats.HistoryTokens

	userInput = strings.TrimSpace(userInput)
	if userInput != "" {
		userInput = textutil.TruncateRunes(userInput, maxUserInputTokens*2)
		lastIsSameUserInput := false
		if len(messages) > 0 {
			last := messages[len(messages)-1]
			lastIsSameUserInput = last.Role == "user" && strings.TrimSpace(last.Content) == userInput
		}
		if lastIsSameUserInput {
			stats.UserInputDedup = true
		} else {
			messages = append(messages, provider.Message{
				Role:    "user",
				Content: userInput,
			})
			stats.UserInputTokens = estimateTokensApprox(userInput)
			stats.EstimatedTokens += stats.UserInputTokens
		}
	}
	stats.TotalMessages = len(messages)

	return messages, stats
}

func buildHistoryFromContextMessages(
	contextMessages []protocol.ContextMessagePayload,
) []provider.Message {
	if len(contextMessages) == 0 {
		return nil
	}

	history := make([]provider.Message, 0, len(contextMessages))
	historyTokenBudget := maxHistoryTokens
	for _, item := range contextMessages {
		content := strings.TrimSpace(item.Content)
		if content == "" {
			continue
		}
		role := "user"
		if item.SenderType == 2 {
			role = "assistant"
		}
		content = textutil.TruncateRunes(content, maxHistoryMsgTokens*2)
		tokens := estimateTokensApprox(content)
		if tokens <= 0 {
			continue
		}
		if tokens > historyTokenBudget {
			content = textutil.TruncateRunes(content, historyTokenBudget*2)
			tokens = estimateTokensApprox(content)
			if tokens <= 0 {
				break
			}
		}
		history = append(history, provider.Message{
			Role:    role,
			Content: content,
		})
		historyTokenBudget -= tokens
		if historyTokenBudget <= 0 {
			break
		}
	}
	return history
}
