apiVersion: v1
kind: Service
metadata:
  name: aibot-postgres-headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: aibot-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
