apiVersion: v1
kind: Secret
metadata:
  name: aibot-push-files
type: Opaque
stringData:
  AuthKey.p8: |
    -----BEGIN PRIVATE KEY-----
    REPLACE_WITH_REAL_APNS_P8_CONTENT
    -----END PRIVATE KEY-----
  service-account.json: |
    {
      "type": "service_account",
      "project_id": "replace-with-real-project-id"
    }
